### ISSUE TITLE
لتسهيل التحزيم

### ISSUE THREAD

**Issue by yucefsourani** [qussia/Albatar-gnome-Theme#1]
1-الأفضل توفير معلومات عن رقم إصدار الثيم .

2-الأفضل عدم إستخدام المساحات الفارغة في أسماء الملفات مثل ملف السورس .

3-الأفضل أن يكون إسم ملف السورس ذاته إسم الثيم .

4- يجب أن يكون المجلد  الذي يحتوي ملفات الثيم موجود بشكل مباشر داخل الملف السورس المضغوط وليس مجلد داخل مجلد أو مجلد داخل ملف مضغوط أخر ويفضل أيضا أن يكون بذات إسم الثيم.

5-إذا كان الثيم يحتاج إعتماديات مثل Murrine engine الأفضل ذكرهم.

أخيرا شكرا لك

**Comment by QusaiHroub** [comment]
الشكر لك
